### ISSUE TITLE
AttributeError: function 'ckdtree_init_float' not found

### ISSUE THREAD

**Issue by fanweiya** [mortacious/numba-kdtree#2]
```
  File "G:/detect/openvino_pyinstaller/detection_taipanlan3_new_OV_GPU/detect_slice.py", line 17, in <module>
    from numba_kdtree import KDTree
  File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\__init__.py", line 1, in <module>
    from .kd_tree import KDTree
  File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 8, in <module>
    from .ckdtree_ctypes import ckdtree as ckdtree_ct
  File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\ckdtree_ctypes.py", line 46, in <module>
    """)
  File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\ckdtree_ctypes.py", line 32, in _define_functions
    eval(compile(fmt_str.format(c_type=c_type, numba_type=numba_type.name), '<string>', 'exec'))
  File "<string>", line 2, in <module>
  File "F:\Anaconda\envs\tf2\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "F:\Anaconda\envs\tf2\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'ckdtree_init_float' not found
```

**Comment by fanweiya** [comment]
@mortacious I’ve updated the latest version, but there are still bugs.

**Comment by mortacious** [comment]
I just tested the current version again in a fresh windows environment with `numba-kdtree` and all dependencies installed with `pip` and everything ran smoothly:

```# Name                    Version                   Build  Channel
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
llvmlite                  0.37.0                   pypi_0    pypi
more-itertools            8.11.0             pyhd8ed1ab_0    conda-forge
numba                     0.54.1                   pypi_0    pypi
numba-kdtree              0.1.1                    pypi_0    pypi
numpy                     1.20.0                   pypi_0    pypi
openssl                   3.0.0                h8ffe710_2    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py38haa244fe_2    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pytest                    6.2.5            py38haa244fe_1    conda-forge
python                    3.8.12          h900ac77_2_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
scipy                     1.7.2                    pypi_0    pypi
setuptools                59.1.0           py38haa244fe_0    conda-forge
sqlite                    3.36.0               h8ffe710_2    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
```
Could you give more details about your problem, your environment and a minimal example to reproduce for me?

**Comment by fanweiya** [comment]
@mortacious 
```
Traceback (most recent call last):
  File "G:/detect/openvino_pyinstaller/openvino_slice_huizhong/detect_slice_updata.py", line 503, in <module>
    iou_thres=iou_thrd,cutoff_distance=16,device=cpu_select,area_thrd=area_thrd)
  File "G:/detect/openvino_pyinstaller/openvino_slice_huizhong/detect_slice_updata.py", line 337, in get_sliced_prediction
    group_num, group_list, all_cell_info = groupcomputer(cell_info, distance_tred=distance_tred)
  File "G:\detect\openvino_pyinstaller\openvino_slice_huizhong\utils\general.py", line 78, in groupcomputer
    dist, index = tree.query([centerlist[ind]], k=topk)
  File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 87, in query
    return _KDTree_query(self, X, k, p, eps, distance_upper_bound, n_jobs)
  File "F:\Anaconda\envs\tf2\lib\site-packages\numba\core\dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "F:\Anaconda\envs\tf2\lib\site-packages\numba\core\dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
No implementation of function Function(<function _ol_query at 0x000002DA42EEDEE8>) found for signature:

 >>> _ol_query(numba.KDTreeType(('ckdtree', uint64), ('root_bbox', array(float64, 2d, C)), ('data', array(float64, 2d, C)), ('idx', array(int64, 1d, C))), reflected list(array(float64, 1d, C))<iv=None>, k=int64, p=float64, eps=float64, distance_upper_bound=float64)

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function '_ol_query': File: numba_kdtree\kd_tree.py: Line 194.
    With argument(s): '(numba.KDTreeType(('ckdtree', uint64), ('root_bbox', array(float64, 2d, C)), ('data', array(float64, 2d, C)), ('idx', array(int64, 1d, C))), reflected list(array(float64, 1d, C))<iv=None>, k=int64, p=float64, eps=float64, distance_upper_bound=float64)':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   Unknown attribute 'reshape' of type reflected list(array(float64, 1d, C))<iv=None>
   
   File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 208:
       def _query_impl(self, X, k=1, p=2, eps=0.0, distance_upper_bound=np.inf):
           <source elided>
           n_features = self.data.shape[1]
           xx = np.ascontiguousarray(X.reshape(-1, n_features)).astype(dtype_npy)
           ^
   
   During: typing of get attribute at F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py (208)
   
   File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 208:
       def _query_impl(self, X, k=1, p=2, eps=0.0, distance_upper_bound=np.inf):
           <source elided>
           n_features = self.data.shape[1]
           xx = np.ascontiguousarray(X.reshape(-1, n_features)).astype(dtype_npy)
           ^

  raised from F:\Anaconda\envs\tf2\lib\site-packages\numba\core\typeinfer.py:1074

- Resolution failure for non-literal arguments:
None

During: resolving callee type: BoundFunction((<class 'numba_kdtree.kd_tree.KDTreeType'>, 'query') for numba.KDTreeType(('ckdtree', uint64), ('root_bbox', array(float64, 2d, C)), ('data', array(float64, 2d, C)), ('idx', array(int64, 1d, C))))
During: typing of call at F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py (130)


File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 130:
def _KDTree_query(self, X, k=1, p=2, eps=0.0, distance_upper_bound=np.inf, n_jobs=1):
    <source elided>
    if n_jobs == 1:
        return self.query(X, k=k, p=p, eps=eps, distance_upper_bound=distance_upper_bound)
        ^

```

**Comment by mortacious** [comment]
Your problem is caused by a wrong call of the `query` function. Numba expects the `X` parameter to be compatible with a numpy array. However, you are actually passing a list of arrays with the call `tree.query([centerlist[ind]], k=topk)`. 
This causes problems because numba cannot convert such a list directly into an array like numpy can with `asarray`. 

I added an automatic conversion of lists in the latest version (0.1.2). This should fix your problem.

**Comment by fanweiya** [comment]
Thank you. The latest version is working fine.

**Comment by fanweiya** [comment]
@mortacious 
```
F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py:160: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'X' of function '_ol_query.<locals>._query_impl'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 245:

    def _query_impl(self, X, k=1, p=2, eps=0.0, distance_upper_bound=np.inf):
    ^

  return self.query(X, k=k, p=p, eps=eps, distance_upper_bound=distance_upper_bound)
F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py:160: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'X' of function '_convert_to_valid_input.<locals>._convert_impl'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 60:

    def _convert_impl(X, n_features, dtype):
    ^

  return self.query(X, k=k, p=p, eps=eps, distance_upper_bound=distance_upper_bound)
F:\Anaconda\envs\tf2\lib\site-packages\numba\core\ir_utils.py:2139: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'X' of function '_KDTree_query'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 159:
@nb.njit()
def _KDTree_query(self, X, k=1, p=2, eps=0.0, distance_upper_bound=np.inf):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
F:\Anaconda\envs\tf2\lib\site-packages\numba\core\ir_utils.py:2139: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'X' of function '_ol_query.<locals>._query_impl'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 245:

    def _query_impl(self, X, k=1, p=2, eps=0.0, distance_upper_bound=np.inf):
    ^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
```

**Comment by fanweiya** [comment]
@mortacious 
```
F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py:160: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'X' of function '_ol_query.<locals>._query_impl'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 245:

    def _query_impl(self, X, k=1, p=2, eps=0.0, distance_upper_bound=np.inf):
    ^

  return self.query(X, k=k, p=p, eps=eps, distance_upper_bound=distance_upper_bound)
F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py:160: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'X' of function '_convert_to_valid_input.<locals>._convert_impl'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 60:

    def _convert_impl(X, n_features, dtype):
    ^

  return self.query(X, k=k, p=p, eps=eps, distance_upper_bound=distance_upper_bound)
F:\Anaconda\envs\tf2\lib\site-packages\numba\core\ir_utils.py:2139: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'X' of function '_KDTree_query'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 159:
@nb.njit()
def _KDTree_query(self, X, k=1, p=2, eps=0.0, distance_upper_bound=np.inf):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
F:\Anaconda\envs\tf2\lib\site-packages\numba\core\ir_utils.py:2139: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'X' of function '_ol_query.<locals>._query_impl'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "F:\Anaconda\envs\tf2\lib\site-packages\numba_kdtree\kd_tree.py", line 245:

    def _query_impl(self, X, k=1, p=2, eps=0.0, distance_upper_bound=np.inf):
    ^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
```

**Comment by mortacious** [comment]
I don't think this is a problem I can fix here. numba will eventually replace the `reflected_list` with the `typed.List` type. However, currently numba generates a `reflected_list` when a list is passed from the python side. 

If you want to avoid the warnings, you should pass a typed list:
```python
tree.query(numba.typed.List([centerlist[ind]]), k=topk)
```
or use the numpy array directly:
```python
tree.query(centerlist[ind], k=topk)
```

I have just pushed the support for `typed.List`.
